//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadenaRestaurantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenes
    {
        public int DetalleID { get; set; }
        public int OrdenID { get; set; }
        public int PlatilloID { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
        public virtual Platillos Platillos { get; set; }
    }
}
