//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadenaRestaurantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        public Ordenes()
        {
            this.DetalleOrdenes = new HashSet<DetalleOrdenes>();
        }
    
        public int OrdenID { get; set; }
        public int MesaID { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<DetalleOrdenes> DetalleOrdenes { get; set; }
    }
}
